import type { Meta, StoryObj } from "@storybook/react-vite";

import { mocked } from "storybook/test";
import { Name } from "../Name";
import { getRandomName } from "../Utils";

const meta = {
  title: "Mocks/Name",
  component: Name,
} satisfies Meta<typeof Name>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Random values are generated by the getRandomName function.
 *
 * IF DATA come from an API, we can use the beforeEach hook to mock the data with mockResolvedValue
 *
 * If the data is static, we can use the mockReturnValueOnce to return the data only once.
 */
export const Default: Story = {};

export const WithMockData: Story = {
  beforeEach: () => {
    mocked(getRandomName).mockReturnValue("Fixed Name");
  },
};
